---
- name: Get the latest McFly release version
  ansible.builtin.shell: |
    set -o pipefail
    curl -s https://github.com/cantino/mcfly/releases/latest | cut -d'"' -f2 | rev | cut -d'/' -f1 | rev
  register: omz_mcfly_latest_version
  when: omz_mcfly_version == "latest"
  tags:
    - omz
    - mcfly

- name: Get the McFly release version
  ansible.builtin.debug:
    msg: "{{ omz_mcfly_version }}"
  tags:
    - omz
    - mcfly

- name: Download latest McFly release
  ansible.builtin.get_url:
    url: "https://github.com/cantino/mcfly/releases/download/{{ omz_mcfly_latest_version.stdout }}/mcfly-{{ omz_mcfly_latest_version.stdout }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/mcfly.tar.gz"
    mode: 0640
    force: true
  when: omz_mcfly_version == "latest"
  tags:
    - omz
    - mcfly

- name: Download McFly release
  ansible.builtin.get_url:
    url: "https://github.com/cantino/mcfly/releases/download/{{ omz_mcfly_version }}/mcfly-{{ omz_mcfly_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/mcfly.tar.gz"
    mode: 0640
    force: true
  when: omz_mcfly_version != "latest"

- name: Unarchive downloaded package
  ansible.builtin.unarchive:
    src: "/tmp/mcfly.tar.gz"
    dest: "/tmp"
  tags:
    - omz
    - mcfly

- name: Install binary to /usr/local/bin/mcfly
  ansible.builtin.copy:
    src: /tmp/mcfly
    remote_src: true
    dest: /usr/local/bin/mcfly
    owner: root
    group: root
    mode: 0755
  become: true
  tags:
    - omz
    - mcfly
