---
- name: Install Zsh Shell packages on Debian based distro
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Install Zsh Shell packages on RedHat based distro
  ansible.builtin.yum:
    name: zsh
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Ensure git package is installed on Debian based distro
  ansible.builtin.apt:
    name: git
    state: present
  become: true
  when: ansible_os_family == 'Debian'

- name: Ensure git package is installed on RedHat based distro
  ansible.builtin.yum:
    name: git
    state: present
  become: true
  when: ansible_os_family == 'RedHat'

- name: Clone Oh-My-Zsh repository to user's home folder
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ item }}/.oh-my-zsh
  with_items: "{{ omz_users }}"

- name: Clone Oh-My-Zsh repository to root home folder
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /root/.oh-my-zsh
  become: true
  when: omz_root

- name: Clone zsh-autosuggestions plugin repository for users
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /home/{{ item }}/.oh-my-zsh/plugins/zsh-autosuggestions
  with_items: "{{ omz_users }}"

- name: Clone zsh-autosuggestions plugin repository for root
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /root/.oh-my-zsh/plugins/zsh-autosuggestions
  become: true
  when: omz_root

- name: Copy .zshrc template to user's home folder
  ansible.builtin.template:
    src: zshrc.j2
    dest: /home/{{ item }}/.zshrc
    mode: 0640
    backup: true
  with_items: "{{ omz_users }}"

- name: Copy .zshrc template to root home folder
  ansible.builtin.template:
    src: zshrc.j2
    dest: /root/.zshrc
    mode: 0640
    backup: true
  become: true
  when: omz_root

- name: Setup user permissions for .oh-my-zsh dir
  ansible.builtin.file:
    path: /home/{{ item }}/.oh-my-zsh
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  with_items: "{{ omz_users }}"

- name: Setup user permissions for .zshrc file
  ansible.builtin.file:
    path: /home/{{ item }}/.zshrc
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0640
  with_items: "{{ omz_users }}"

- name: Change default shell to Zsh for users
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ omz_zsh_path }}"
  with_items: "{{ omz_users }}"
  become: true
  when: omz_chsh

- name: Change default shell to Zsh for root
  ansible.builtin.user:
    name: root
    shell: "{{ omz_zsh_path }}"
  become: true
  when: omz_chsh and omz_root
